name: gym_app_mobile
description: "A mobile app for the gym."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.13.0

dependencies:
  dio: ^5.11.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^11.0.0
  intl: ^0.20.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
